final List<Map<String, dynamic>> financial_statements = [
  {
    "Financial Statements": {
      "description": "Financial Statements",
      "marks": 30,
      "questions": [
        {
          "question":
              "Which financial statement provides a summary of revenues and expenses over a period of time?",
          "options": [
            "Balance Sheet",
            "Income Statement",
            "Cash Flow Statement",
            "Trial Balance"
          ],
          "answer": "Income Statement"
        },
        {
          "question": "Which section of the balance sheet lists liabilities?",
          "options": ["Assets", "Equity", "Liabilities", "Revenue"],
          "answer": "Liabilities"
        },
        {
          "question": "What does 'Retained Earnings' represent?",
          "options": [
            "Total revenue generated by a company",
            "Profits reinvested in the business",
            "Cash available for investment",
            "Total assets owned by a company"
          ],
          "answer": "Profits reinvested in the business"
        },
        {
          "question":
              "Which financial statement shows the movement of cash within a business?",
          "options": [
            "Balance Sheet",
            "Income Statement",
            "Cash Flow Statement",
            "Statement of Changes in Equity"
          ],
          "answer": "Cash Flow Statement"
        },
        {
          "question":
              "Which of the following accounts is NOT classified as an expense?",
          "options": [
            "Salaries",
            "Depreciation",
            "Accounts Payable",
            "Advertising Costs"
          ],
          "answer": "Accounts Payable"
        },
        {
          "question": "What does 'Working Capital' measure?",
          "options": [
            "Long-term financial stability",
            "Company profitability",
            "Difference between current assets and liabilities",
            "Total value of shareholder investments"
          ],
          "answer": "Difference between current assets and liabilities"
        },
        {
          "question":
              "Which of the following financial statements explains changes in a company's equity?",
          "options": [
            "Income Statement",
            "Balance Sheet",
            "Statement of Changes in Equity",
            "Cash Flow Statement"
          ],
          "answer": "Statement of Changes in Equity"
        },
        {
          "question": "Depreciation is recorded in which financial statement?",
          "options": [
            "Balance Sheet",
            "Income Statement",
            "Cash Flow Statement",
            "Trial Balance"
          ],
          "answer": "Income Statement"
        },
        {
          "question": "Which of these is considered a non-current asset?",
          "options": ["Accounts Receivable", "Inventory", "Buildings", "Cash"],
          "answer": "Buildings"
        },
        {
          "question":
              "Which principle requires that expenses be recorded in the same period as the revenue they help generate?",
          "options": [
            "Accrual Principle",
            "Matching Principle",
            "Conservatism Principle",
            "Revenue Recognition Principle"
          ],
          "answer": "Matching Principle"
        }
      ]
    }
  }
];

final List<Map<String, dynamic>> managerial_accounting = [
  {
    "Managerial Accounting": {
      "description": "Managerial Accounting",
      "marks": 60,
      "questions": [
        {
          "question":
              "Which financial statement is primarily used for internal decision-making in managerial accounting?",
          "options": [
            "Balance Sheet",
            "Income Statement",
            "Statement of Cash Flows",
            "None of the above"
          ],
          "answer": "None of the above"
        },
        {
          "question":
              "Which costing method assigns costs based on activities performed?",
          "options": [
            "Absorption Costing",
            "Job Order Costing",
            "Activity-Based Costing",
            "Variable Costing"
          ],
          "answer": "Activity-Based Costing"
        },
        {
          "question":
              "Which of the following is a direct cost in a manufacturing business?",
          "options": [
            "Factory rent",
            "Depreciation on machinery",
            "Raw materials",
            "Administrative salaries"
          ],
          "answer": "Raw materials"
        },
        {
          "question": "A contribution margin is calculated as:",
          "options": [
            "Sales Revenue - Fixed Costs",
            "Sales Revenue - Variable Costs",
            "Sales Revenue ÷ Total Costs",
            "Total Costs - Operating Expenses"
          ],
          "answer": "Sales Revenue - Variable Costs"
        },
        {
          "question":
              "Which of the following budgets is prepared first in a master budget?",
          "options": [
            "Cash Budget",
            "Sales Budget",
            "Production Budget",
            "Operating Budget"
          ],
          "answer": "Sales Budget"
        },
        {
          "question": "The term 'relevant cost' in decision-making refers to:",
          "options": [
            "Sunk costs",
            "Costs that do not change",
            "Costs that affect future decisions",
            "Historical costs"
          ],
          "answer": "Costs that affect future decisions"
        },
        {
          "question":
              "In variance analysis, what does a favorable variance indicate?",
          "options": [
            "Actual costs were higher than budgeted costs",
            "Actual costs were lower than budgeted costs",
            "Revenues were lower than expected",
            "No difference between budgeted and actual results"
          ],
          "answer": "Actual costs were lower than budgeted costs"
        },
        {
          "question":
              "Which of the following is NOT an example of a fixed cost?",
          "options": [
            "Depreciation on factory equipment",
            "Supervisor salaries",
            "Direct materials",
            "Factory rent"
          ],
          "answer": "Direct materials"
        },
        {
          "question":
              "Which of the following is an advantage of decentralization in managerial accounting?",
          "options": [
            "Reduces decision-making speed",
            "Provides greater control at top management",
            "Improves decision-making at lower levels",
            "Reduces accountability of business units"
          ],
          "answer": "Improves decision-making at lower levels"
        },
        {
          "question": "What is the main purpose of a flexible budget?",
          "options": [
            "To adjust expenses based on actual activity levels",
            "To predict cash flows",
            "To allocate financial resources",
            "To evaluate long-term investments"
          ],
          "answer": "To adjust expenses based on actual activity levels"
        }
      ]
    }
  }
];

final List<Map<String, dynamic>> cost_accounting = [
  {
    "Cost Accounting": {
      "description": "Cost Accounting",
      "marks": 30,
      "questions": [
        {
          "question": "Which of the following is considered a direct cost?",
          "options": [
            "Factory Rent",
            "Direct Materials",
            "Marketing Expenses",
            "Administrative Salaries"
          ],
          "answer": "Direct Materials"
        },
        {
          "question": "Which cost is classified as a period cost?",
          "options": [
            "Direct Labor",
            "Factory Overheads",
            "Selling and Administrative Expenses",
            "Direct Materials"
          ],
          "answer": "Selling and Administrative Expenses"
        },
        {
          "question":
              "Which cost classification includes both fixed and variable costs?",
          "options": [
            "Direct Cost",
            "Overhead Cost",
            "Mixed Cost",
            "Indirect Cost"
          ],
          "answer": "Mixed Cost"
        },
        {
          "question":
              "Which costing method assigns fixed manufacturing overhead to each unit produced?",
          "options": [
            "Variable Costing",
            "Absorption Costing",
            "Direct Costing",
            "Job Costing"
          ],
          "answer": "Absorption Costing"
        },
        {
          "question": "Prime costs are made up of:",
          "options": [
            "Direct Materials and Direct Labor",
            "Direct Labor and Overhead",
            "Fixed and Variable Costs",
            "Total Costs - Selling Expenses"
          ],
          "answer": "Direct Materials and Direct Labor"
        },
        {
          "question":
              "What type of cost remains unchanged in total regardless of changes in production volume?",
          "options": [
            "Fixed Cost",
            "Variable Cost",
            "Mixed Cost",
            "Direct Cost"
          ],
          "answer": "Fixed Cost"
        },
        {
          "question":
              "Which of the following is an example of a variable cost?",
          "options": [
            "Factory Rent",
            "Depreciation",
            "Raw Materials",
            "Supervisor's Salary"
          ],
          "answer": "Raw Materials"
        },
        {
          "question":
              "Which costing system is most suitable for a manufacturing company producing unique custom orders?",
          "options": [
            "Process Costing",
            "Job Order Costing",
            "Absorption Costing",
            "Standard Costing"
          ],
          "answer": "Job Order Costing"
        },
        {
          "question": "What is the main purpose of cost accounting?",
          "options": [
            "To prepare tax returns",
            "To record financial transactions",
            "To determine the cost of production and control expenses",
            "To prepare financial statements"
          ],
          "answer": "To determine the cost of production and control expenses"
        },
        {
          "question":
              "Which type of cost is treated as part of inventory until the goods are sold?",
          "options": ["Period Cost", "Product Cost", "Fixed Cost", "Sunk Cost"],
          "answer": "Product Cost"
        }
      ]
    }
  }
];

final List<Map<String, dynamic>> bank_reconciliation = [
  {
    "Bank Reconciliation": {
      "description": "Bank Reconciliation",
      "marks": 30,
      "questions": [
        {
          "question": "What is the purpose of a bank reconciliation statement?",
          "options": [
            "To record transactions",
            "To verify cash book and bank statement differences",
            "To audit financial records",
            "To calculate net profit"
          ],
          "answer": "To verify cash book and bank statement differences"
        },
        {
          "question":
              "Which of the following appears in the bank reconciliation statement but NOT in the cash book?",
          "options": [
            "Deposits in Transit",
            "Bank Charges",
            "Unrecorded Cheques",
            "Outstanding Deposits"
          ],
          "answer": "Deposits in Transit"
        },
        {
          "question": "Which item is an example of an unpresented cheque?",
          "options": [
            "A cheque recorded but not yet cleared by the bank",
            "A cheque issued but already cleared",
            "A cheque received but not deposited",
            "A cheque issued and cancelled"
          ],
          "answer": "A cheque recorded but not yet cleared by the bank"
        },
        {
          "question":
              "What happens to outstanding deposits in a bank reconciliation?",
          "options": [
            "They are added to the bank balance",
            "They are deducted from the cash book",
            "They are removed from the bank statement",
            "They are deducted from the bank balance"
          ],
          "answer": "They are added to the bank balance"
        },
        {
          "question":
              "If a company's bank statement shows an overdraft, what does this mean?",
          "options": [
            "The company has extra cash",
            "The company owes the bank money",
            "The company has deposited too much",
            "The company has an error in the records"
          ],
          "answer": "The company owes the bank money"
        },
        {
          "question":
              "Which of the following will NOT cause a difference between the cash book and the bank statement?",
          "options": [
            "Outstanding deposits",
            "Unrecorded bank charges",
            "Incorrect bank reconciliation",
            "Deposits in transit"
          ],
          "answer": "Incorrect bank reconciliation"
        },
        {
          "question":
              "Why might a company’s bank statement show a lower balance than its cash book?",
          "options": [
            "The company has more outstanding deposits",
            "The company recorded a cheque that has not cleared",
            "The bank made an error",
            "The company has no transactions"
          ],
          "answer": "The company recorded a cheque that has not cleared"
        },
        {
          "question":
              "Which of the following items is added to the adjusted bank balance in a reconciliation?",
          "options": [
            "Outstanding cheques",
            "Deposits in transit",
            "Bank fees",
            "Interest charges"
          ],
          "answer": "Deposits in transit"
        },
        {
          "question":
              "How is a bank error handled in a bank reconciliation statement?",
          "options": [
            "It is ignored",
            "It is corrected in the cash book",
            "It is added to the bank statement balance",
            "It is adjusted by the bank in the future"
          ],
          "answer": "It is added to the bank statement balance"
        },
        {
          "question": "What does a bank reconciliation help a company to do?",
          "options": [
            "Track missing transactions",
            "Determine the net profit",
            "File tax returns",
            "Issue financial reports"
          ],
          "answer": "Track missing transactions"
        }
      ]
    }
  }
];

final List<Map<String, dynamic>> taxation = [
  {
    "Taxation": {
      "description": "Taxation",
      "marks": 60,
      "questions": [
        {
          "question":
              "Which tax is applied when an individual sells a property at a profit?",
          "options": [
            "Value-Added Tax (VAT)",
            "Capital Gains Tax",
            "Corporate Tax",
            "PAYE"
          ],
          "answer": "Capital Gains Tax"
        },
        {
          "question":
              "Which tax is charged on imported goods to protect local industries?",
          "options": ["Income Tax", "Excise Duty", "Customs Duty", "PAYE"],
          "answer": "Customs Duty"
        },
        {
          "question":
              "What type of tax is paid by businesses on the goods they sell?",
          "options": [
            "Capital Gains Tax",
            "Corporate Tax",
            "Value-Added Tax (VAT)",
            "Property Tax"
          ],
          "answer": "Value-Added Tax (VAT)"
        },
        {
          "question":
              "Which tax is levied on alcoholic beverages and tobacco products?",
          "options": ["Customs Duty", "Excise Duty", "PAYE", "Corporate Tax"],
          "answer": "Excise Duty"
        },
        {
          "question":
              "Which document is required for businesses to register for tax with SARS?",
          "options": [
            "Income Statement",
            "Tax Clearance Certificate",
            "Company Registration Certificate",
            "Bank Statement"
          ],
          "answer": "Company Registration Certificate"
        },
        {
          "question":
              "Which tax is applicable when buying a new car in South Africa?",
          "options": [
            "Import Duty",
            "Fuel Levy",
            "Value-Added Tax (VAT)",
            "Customs Duty"
          ],
          "answer": "Value-Added Tax (VAT)"
        },
        {
          "question": "What is the main purpose of taxation?",
          "options": [
            "To fund government expenses",
            "To increase corporate profits",
            "To reduce the number of businesses",
            "To regulate bank interest rates"
          ],
          "answer": "To fund government expenses"
        },
        {
          "question": "What is a progressive tax system?",
          "options": [
            "A tax system where everyone pays the same amount",
            "A tax system where tax rates decrease as income increases",
            "A tax system where tax rates increase as income increases",
            "A tax system that only applies to companies"
          ],
          "answer": "A tax system where tax rates increase as income increases"
        },
        {
          "question":
              "Which tax is imposed on estates of deceased individuals?",
          "options": [
            "Estate Duty",
            "Capital Gains Tax",
            "Corporate Tax",
            "Property Tax"
          ],
          "answer": "Estate Duty"
        },
        {
          "question":
              "Which tax is deducted by employers from employees' salaries and paid to SARS?",
          "options": [
            "Corporate Tax",
            "Provisional Tax",
            "Pay-As-You-Earn (PAYE)",
            "Excise Duty"
          ],
          "answer": "Pay-As-You-Earn (PAYE)"
        }
      ]
    }
  }
];

final List<Map<String, dynamic>> budgeting = [
  {
    "Budgeting": {
      "description": "Budgeting",
      "marks": 30,
      "questions": [
        {
          "question": "What is the main advantage of a budget?",
          "options": [
            "It ensures 100% accuracy in financial planning",
            "It helps in setting financial goals and controlling expenses",
            "It eliminates all financial risks",
            "It guarantees business profitability"
          ],
          "answer":
              "It helps in setting financial goals and controlling expenses"
        },
        {
          "question": "Which of the following is NOT a component of a budget?",
          "options": ["Income", "Expenses", "Assets", "Savings"],
          "answer": "Assets"
        },
        {
          "question": "A cash budget primarily focuses on:",
          "options": [
            "Predicting revenue growth",
            "Tracking long-term asset investments",
            "Monitoring cash inflows and outflows",
            "Estimating tax liabilities"
          ],
          "answer": "Monitoring cash inflows and outflows"
        },
        {
          "question": "What is incremental budgeting?",
          "options": [
            "Starting from zero and justifying each expense",
            "Making small adjustments to the previous year’s budget",
            "Creating a budget without considering past data",
            "Allocating funds only for essential activities"
          ],
          "answer": "Making small adjustments to the previous year’s budget"
        },
        {
          "question":
              "Which budgeting method prioritizes every expense based on necessity?",
          "options": [
            "Zero-Based Budgeting",
            "Cash Budgeting",
            "Incremental Budgeting",
            "Fixed Budgeting"
          ],
          "answer": "Zero-Based Budgeting"
        },
        {
          "question":
              "Which type of budget helps a business determine its future financing needs?",
          "options": [
            "Operational Budget",
            "Cash Budget",
            "Capital Budget",
            "Master Budget"
          ],
          "answer": "Cash Budget"
        },
        {
          "question":
              "The process of comparing actual financial performance with budgeted amounts is called:",
          "options": [
            "Budget Allocation",
            "Variance Analysis",
            "Financial Auditing",
            "Expense Forecasting"
          ],
          "answer": "Variance Analysis"
        },
        {
          "question":
              "Which type of budget provides a complete financial plan for the entire business?",
          "options": [
            "Departmental Budget",
            "Master Budget",
            "Cash Budget",
            "Rolling Budget"
          ],
          "answer": "Master Budget"
        },
        {
          "question": "Which factor is most important when preparing a budget?",
          "options": [
            "Past financial performance",
            "Expected future income and expenses",
            "Industry trends",
            "Competitor budgets"
          ],
          "answer": "Expected future income and expenses"
        },
        {
          "question":
              "What is the primary purpose of variance analysis in budgeting?",
          "options": [
            "To eliminate all financial risks",
            "To identify differences between actual and budgeted figures",
            "To adjust tax rates",
            "To create new financial statements"
          ],
          "answer":
              "To identify differences between actual and budgeted figures"
        }
      ]
    }
  }
];

final List<Map<String, dynamic>> internal_auditing = [
  {
    "Internal Auditing & Control": {
      "description": "Internal Auditing & Control",
      "marks": 60,
      "questions": [
        {
          "question":
              "Which principle is fundamental to an effective internal control system?",
          "options": [
            "Maximizing revenue",
            "Ensuring external audit compliance",
            "Establishing checks and balances",
            "Following tax laws"
          ],
          "answer": "Establishing checks and balances"
        },
        {
          "question": "What is the primary role of an internal auditor?",
          "options": [
            "To investigate criminal fraud cases",
            "To assist in external audits",
            "To evaluate and improve business operations",
            "To calculate corporate tax obligations"
          ],
          "answer": "To evaluate and improve business operations"
        },
        {
          "question":
              "Which internal control measure helps prevent employee fraud?",
          "options": [
            "Mandatory vacation policies",
            "Annual revenue analysis",
            "Government compliance audits",
            "Financial forecasting"
          ],
          "answer": "Mandatory vacation policies"
        },
        {
          "question":
              "What is the primary objective of risk assessment in internal control?",
          "options": [
            "To identify and address potential risks",
            "To ensure compliance with external auditors",
            "To review financial statements",
            "To reduce company expenses"
          ],
          "answer": "To identify and address potential risks"
        },
        {
          "question":
              "Which document provides guidelines for internal auditing procedures?",
          "options": [
            "Financial Statements Report",
            "Generally Accepted Accounting Principles (GAAP)",
            "Internal Audit Charter",
            "Shareholder Agreement"
          ],
          "answer": "Internal Audit Charter"
        },
        {
          "question":
              "What does the term 'segregation of duties' mean in internal control?",
          "options": [
            "Employees should specialize in one department",
            "Tasks and responsibilities should be divided to reduce risk",
            "Only senior management can approve financial reports",
            "All employees should be cross-trained"
          ],
          "answer":
              "Tasks and responsibilities should be divided to reduce risk"
        },
        {
          "question":
              "Which internal control procedure helps detect discrepancies in financial records?",
          "options": [
            "Inventory valuation",
            "Regular account reconciliations",
            "Annual corporate meetings",
            "Tax audits"
          ],
          "answer": "Regular account reconciliations"
        },
        {
          "question": "Why is an internal audit considered independent?",
          "options": [
            "Internal auditors report directly to government agencies",
            "Internal auditors do not take instructions from management",
            "Internal audits are performed by third parties",
            "Internal audits follow external auditor recommendations"
          ],
          "answer": "Internal auditors do not take instructions from management"
        },
        {
          "question": "What is a major limitation of internal control systems?",
          "options": [
            "They eliminate all risks",
            "They ensure 100% fraud prevention",
            "They require constant monitoring and updates",
            "They are only applicable to financial data"
          ],
          "answer": "They require constant monitoring and updates"
        },
        {
          "question":
              "Which factor can weaken the effectiveness of internal controls?",
          "options": [
            "Strong ethical culture in the organization",
            "Collusion between employees",
            "Strict regulatory compliance",
            "Annual management reviews"
          ],
          "answer": "Collusion between employees"
        }
      ]
    }
  }
];

final List<Map<String, dynamic>> business_transactions = [
  {
    "Business Transactions": {
      "description": "Business Transactions",
      "marks": 60,
      "questions": [
        {
          "question":
              "Which of the following is an example of a business transaction?",
          "options": [
            "Hiring an employee",
            "Purchasing inventory",
            "Setting company goals",
            "Changing company policies"
          ],
          "answer": "Purchasing inventory"
        },
        {
          "question":
              "Which type of account is affected when a company pays rent?",
          "options": ["Revenue", "Asset", "Liability", "Expense"],
          "answer": "Expense"
        },
        {
          "question": "A credit sale affects which accounts?",
          "options": [
            "Cash and Sales Revenue",
            "Accounts Receivable and Sales Revenue",
            "Inventory and Cash",
            "Liabilities and Expenses"
          ],
          "answer": "Accounts Receivable and Sales Revenue"
        },
        {
          "question":
              "Which document is issued when a business sells goods on credit?",
          "options": ["Invoice", "Receipt", "Bank Statement", "Trial Balance"],
          "answer": "Invoice"
        },
        {
          "question":
              "What is the double-entry rule for recording transactions?",
          "options": [
            "Every debit has a corresponding credit",
            "Every transaction must be recorded three times",
            "Assets should always be greater than liabilities",
            "Revenues must always exceed expenses"
          ],
          "answer": "Every debit has a corresponding credit"
        },
        {
          "question":
              "Which account increases when a business receives cash from a customer?",
          "options": [
            "Accounts Payable",
            "Accounts Receivable",
            "Cash",
            "Revenue"
          ],
          "answer": "Cash"
        },
        {
          "question": "What happens when a business buys equipment on credit?",
          "options": [
            "Assets increase and liabilities increase",
            "Assets increase and owner's equity decreases",
            "Expenses increase and revenue decreases",
            "Liabilities decrease and assets decrease"
          ],
          "answer": "Assets increase and liabilities increase"
        },
        {
          "question":
              "Which financial statement shows a company’s financial position at a specific date?",
          "options": [
            "Income Statement",
            "Cash Flow Statement",
            "Balance Sheet",
            "Statement of Retained Earnings"
          ],
          "answer": "Balance Sheet"
        },
        {
          "question":
              "What type of transaction occurs when a company pays off a loan?",
          "options": [
            "Capital Expenditure",
            "Operating Activity",
            "Financing Activity",
            "Investing Activity"
          ],
          "answer": "Financing Activity"
        },
        {
          "question": "Which document serves as proof of a cash payment?",
          "options": ["Invoice", "Bank Statement", "Receipt", "Credit Note"],
          "answer": "Receipt"
        }
      ]
    }
  }
];

final List<Map<String, dynamic>> accounting_principles = [
  {
    "Accounting Principles": {
      "description": "Accounting Principles",
      "marks": 30,
      "questions": [
        {
          "question":
              "Which principle requires that revenue should only be recognized when it is earned?",
          "options": [
            "Revenue Recognition Principle",
            "Matching Principle",
            "Cost Principle",
            "Accrual Principle"
          ],
          "answer": "Revenue Recognition Principle"
        },
        {
          "question": "What is the main focus of the Materiality Principle?",
          "options": [
            "Recording only large transactions",
            "Ensuring all transactions, no matter how small, are recorded",
            "Ignoring small amounts that do not significantly impact financial statements",
            "Focusing on cash transactions only"
          ],
          "answer":
              "Ignoring small amounts that do not significantly impact financial statements"
        },
        {
          "question":
              "Which principle states that businesses should separate their personal transactions from business transactions?",
          "options": [
            "Matching Principle",
            "Entity Concept",
            "Going Concern Principle",
            "Consistency Principle"
          ],
          "answer": "Entity Concept"
        },
        {
          "question":
              "The Conservatism Principle advises that businesses should:",
          "options": [
            "Always recognize profits before they are realized",
            "Record expenses and liabilities as soon as possible",
            "Overstate their revenue and assets",
            "Ignore future losses in financial reports"
          ],
          "answer": "Record expenses and liabilities as soon as possible"
        },
        {
          "question":
              "Which accounting principle ensures that similar transactions are recorded consistently across periods?",
          "options": [
            "Consistency Principle",
            "Full Disclosure Principle",
            "Accrual Principle",
            "Objectivity Principle"
          ],
          "answer": "Consistency Principle"
        },
        {
          "question": "The Accrual Principle requires that:",
          "options": [
            "Revenue and expenses are recognized when earned or incurred, not when cash is received or paid",
            "Only cash transactions should be recorded",
            "Profits should always be maximized",
            "Expenses should be ignored"
          ],
          "answer":
              "Revenue and expenses are recognized when earned or incurred, not when cash is received or paid"
        },
        {
          "question":
              "According to the Full Disclosure Principle, businesses must:",
          "options": [
            "Hide financial details from competitors",
            "Only disclose important financial transactions to management",
            "Provide all necessary financial information to users of financial statements",
            "Only report net income and ignore other financial details"
          ],
          "answer":
              "Provide all necessary financial information to users of financial statements"
        },
        {
          "question":
              "Which principle suggests that accounting records should be based on verifiable evidence rather than personal opinions?",
          "options": [
            "Cost Principle",
            "Objectivity Principle",
            "Matching Principle",
            "Accrual Principle"
          ],
          "answer": "Objectivity Principle"
        },
        {
          "question": "The Historical Cost Principle states that:",
          "options": [
            "Assets should be recorded at their original purchase price",
            "Assets should be recorded at current market value",
            "All financial transactions should be recorded in future value",
            "Only intangible assets should be recorded"
          ],
          "answer": "Assets should be recorded at their original purchase price"
        },
        {
          "question":
              "Which accounting principle ensures that businesses record transactions at the time they occur rather than when cash is exchanged?",
          "options": [
            "Accrual Principle",
            "Cash Basis Principle",
            "Going Concern Principle",
            "Materiality Principle"
          ],
          "answer": "Accrual Principle"
        }
      ]
    }
  }
];

final List<Map<String, dynamic>> financial_reporting_evaluation = [
  {
    "Financial Reporting & Evaluation": {
      "description": "Financial Reporting & Evaluation",
      "marks": 30,
      "questions": [
        {
          "question": "What is the main purpose of financial reporting?",
          "options": [
            "To determine tax liabilities",
            "To provide useful financial information to stakeholders",
            "To analyze competitors",
            "To calculate employee salaries"
          ],
          "answer": "To provide useful financial information to stakeholders"
        },
        {
          "question":
              "Which financial statement shows a company's assets, liabilities, and equity?",
          "options": [
            "Income Statement",
            "Balance Sheet",
            "Cash Flow Statement",
            "Statement of Changes in Equity"
          ],
          "answer": "Balance Sheet"
        },
        {
          "question":
              "Which financial statement reports revenue and expenses over a specific period?",
          "options": [
            "Balance Sheet",
            "Income Statement",
            "Cash Flow Statement",
            "Budget Report"
          ],
          "answer": "Income Statement"
        },
        {
          "question": "What is the formula for calculating Gross Profit?",
          "options": [
            "Revenue - Expenses",
            "Revenue - Cost of Sales",
            "Assets - Liabilities",
            "Current Assets - Current Liabilities"
          ],
          "answer": "Revenue - Cost of Sales"
        },
        {
          "question":
              "Which financial ratio measures a company's ability to meet its short-term obligations?",
          "options": [
            "Debt-to-Equity Ratio",
            "Current Ratio",
            "Return on Investment (ROI)",
            "Gross Profit Margin"
          ],
          "answer": "Current Ratio"
        },
        {
          "question": "What does Return on Assets (ROA) measure?",
          "options": [
            "A company’s ability to pay debts",
            "A company’s overall profitability relative to assets",
            "The efficiency of inventory management",
            "The total revenue generated from sales"
          ],
          "answer": "A company’s overall profitability relative to assets"
        },
        {
          "question": "What does EBITDA stand for?",
          "options": [
            "Earnings Before Interest, Tax, Depreciation, and Amortization",
            "Earnings Before Income Tax, Dividends, and Assets",
            "Equity, Balance, Interest, Tax, Depreciation, and Assets",
            "Economic Balance Income Tax Depreciation and Assets"
          ],
          "answer":
              "Earnings Before Interest, Tax, Depreciation, and Amortization"
        },
        {
          "question":
              "Which financial statement helps assess a company's cash inflows and outflows?",
          "options": [
            "Balance Sheet",
            "Income Statement",
            "Cash Flow Statement",
            "Statement of Financial Position"
          ],
          "answer": "Cash Flow Statement"
        },
        {
          "question":
              "Which accounting principle ensures that financial information is presented in a clear and comparable manner?",
          "options": [
            "Going Concern Principle",
            "Consistency Principle",
            "Materiality Principle",
            "Cost Principle"
          ],
          "answer": "Consistency Principle"
        },
        {
          "question": "What does the Debt-to-Equity ratio measure?",
          "options": [
            "The company's ability to generate revenue",
            "The proportion of a company’s debt compared to shareholders' equity",
            "The total assets owned by a company",
            "The number of shares issued by a company"
          ],
          "answer":
              "The proportion of a company’s debt compared to shareholders' equity"
        }
      ]
    }
  }
];
